name: dio_pull_request_checker
description: A github action template for dart action
version: 1.0.0
repository: https://github.com/cfug/dio-pull-request-checker

environment:
  sdk: ^3.0.0

dependencies:
  github_action_context: ^0.2.1
  github_action_core: ^0.2.0
  github: ^9.14.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
